<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="6432" started-at="2016-06-09T06:20:04Z" finished-at="2016-06-09T06:20:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6432" started-at="2016-06-09T06:20:04Z" finished-at="2016-06-09T06:20:10Z">
      <class name="com.psl.guru99.ParameterLogin">
        <test-method status="PASS" signature="testSetup()[pri:0, instance:com.psl.guru99.ParameterLogin@754ba872]" name="testSetup" is-config="true" duration-ms="5951" started-at="2016-06-09T11:50:04Z" finished-at="2016-06-09T11:50:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetup -->
        <test-method status="PASS" signature="QuitBrowser()[pri:0, instance:com.psl.guru99.ParameterLogin@754ba872]" name="QuitBrowser" duration-ms="458" started-at="2016-06-09T11:50:10Z" finished-at="2016-06-09T11:50:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- QuitBrowser -->
        <test-method status="SKIP" signature="VerifyLogin(java.lang.String, java.lang.String)[pri:0, instance:com.psl.guru99.ParameterLogin@754ba872]" name="VerifyLogin" duration-ms="0" started-at="2016-06-09T11:50:10Z" data-provider="Login" finished-at="2016-06-09T11:50:10Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Data Provider public java.util.List com.psl.guru99.ParameterLogin.loginData() must return either Object[][] or Iterator<Object>[], not interface java.util.List]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Data Provider public java.util.List com.psl.guru99.ParameterLogin.loginData() must return either Object[][] or Iterator<Object>[], not interface java.util.List
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:156)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyLogin -->
      </class> <!-- com.psl.guru99.ParameterLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
